// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZVMZ4_B_7RLslpOcXZivV9UbXP8IRLNM',
    appId: '1:557520026727:web:60f550a8829c2b1173a8c2',
    messagingSenderId: '557520026727',
    projectId: 'green-vault',
    authDomain: 'green-vault.firebaseapp.com',
    storageBucket: 'green-vault.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATEmHgz2KnL-HU_0FP3UmjJXlml9eKff0',
    appId: '1:557520026727:android:b316edb482103cbd73a8c2',
    messagingSenderId: '557520026727',
    projectId: 'green-vault',
    storageBucket: 'green-vault.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVrr4cBvOMI6Xv5iWPJymjl_hOA67YKII',
    appId: '1:557520026727:ios:fb9b6291412a440573a8c2',
    messagingSenderId: '557520026727',
    projectId: 'green-vault',
    storageBucket: 'green-vault.appspot.com',
    iosBundleId: 'com.example.greenVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVrr4cBvOMI6Xv5iWPJymjl_hOA67YKII',
    appId: '1:557520026727:ios:178ce6316cedfffa73a8c2',
    messagingSenderId: '557520026727',
    projectId: 'green-vault',
    storageBucket: 'green-vault.appspot.com',
    iosBundleId: 'com.example.greenVault.RunnerTests',
  );
}
